In [128]:
import pandas as pd
import sqlite3

print("SQL Task Started Successfully")

SQL Task Started Successfully

In [129]:
import pandas as pd

df = pd.read_csv("../data/cleaned_superstore.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [130]:
import sqlite3

conn = sqlite3.connect("superstore.db")

print("Database Created Successfully")

Database Created Successfully

In [131]:
df.to_sql(
    "sales",
    conn,
    if_exists="replace",
    index=False
)

print("Data Imported Successfully")

Data Imported Successfully

In [132]:
query = "SELECT * FROM sales LIMIT 5"

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [133]:
query = """
SELECT Category,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0        Furniture  754747.7613
1  Office Supplies  731893.3140
2       Technology  839893.2790

In [134]:
query = """
SELECT [Customer Name]
FROM sales
LIMIT 10
"""

pd.read_sql(query, conn)

   Customer Name
0  Darren Powers
1  Phillina Ober
2  Phillina Ober
3  Phillina Ober
4     Mick Brown
5  Maria Etezadi
6  Maria Etezadi
7  Jack O'Briant
8  Maria Etezadi
9  Maria Etezadi

In [135]:
query = """
SELECT *
FROM sales
WHERE Sales > 500
"""

pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,6,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078
1,9,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-BI-10004632,Office Supplies,Binders,Ibico Hi-Tech Manual Binding System,609.980,2,0.0,274.4910
2,13,US-2023-167199,2023-01-06,2023-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,TEC-PH-10004539,Technology,Phones,Wireless Extenders zBoost YX545 SOHO Signal Bo...,755.960,4,0.0,204.1092
3,23,US-2023-109232,2023-01-13,2023-01-16,Second Class,ND-18370,Natalie DeCherney,Consumer,United States,Mount Pleasant,...,29464,South,FUR-CH-10000422,Furniture,Chairs,Global Highback Leather Tilter in Burgundy,545.940,6,0.0,87.3504
4,30,US-2023-162775,2023-01-13,2023-01-15,Second Class,CS-12250,Chris Selesnick,Corporate,United States,Bossier City,...,71111,South,OFF-ST-10000025,Office Supplies,Storage,Fellowes Stor/Drawer Steel Plus Storage Drawers,572.580,6,0.0,34.3548
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1170,10122,US-2026-145219,2026-12-24,2026-12-25,First Class,RM-19675,Robert Marley,Home Office,United States,Los Angeles,...,90049,West,TEC-CO-10001449,Technology,Copiers,Hewlett Packard LaserJet 3310 Copier,2879.952,6,0.2,1007.9832
1171,10138,US-2026-114055,2026-12-25,2026-12-29,Second Class,MH-18115,Mick Hernandez,Home Office,United States,Huntsville,...,35810,South,OFF-PA-10000994,Office Supplies,Paper,Xerox 1915,629.100,6,0.0,301.9680
1172,10150,US-2026-121741,2026-12-26,2026-12-26,Same Day,YC-21895,Yoseph Carroll,Corporate,United States,Fremont,...,68025,Central,OFF-ST-10004459,Office Supplies,Storage,Tennsco Single-Tier Lockers,750.680,2,0.0,37.5340
1173,10170,US-2026-163979,2026-12-28,2027-01-02,Second Class,KH-16690,Kristen Hastings,Corporate,United States,San Francisco,...,94110,West,OFF-ST-10003208,Office Supplies,Storage,Adjustable Depth Letter/Legal Cart,725.840,4,0.0,210.4936
1174,10173,US-2026-158526,2026-12-29,2027-01-01,Second Class,KH-16360,Katherine Hughes,Consumer,United States,Louisville,...,40214,South,FUR-CH-10002602,Furniture,Chairs,DMI Arturo Collection Mission-style Design Woo...,1207.840,8,0.0,314.0384

In [136]:
query = """
SELECT [Product Name], Sales
FROM sales
ORDER BY Sales DESC
LIMIT 10
"""

pd.read_sql(query, conn)

                                        Product Name      Sales
0  Cisco TelePresence System EX90 Videoconferenci...  22638.480
1              Canon imageCLASS 2200 Advanced Copier  17499.950
2              Canon imageCLASS 2200 Advanced Copier  13999.960
3              Canon imageCLASS 2200 Advanced Copier  11199.968
4              Canon imageCLASS 2200 Advanced Copier  10499.970
5   GBC Ibimaster 500 Manual ProClick Binding System   9892.740
6               Ibico EPK-21 Electric Binding System   9449.950
7   3D Systems Cube Printer, 2nd Generation, Magenta   9099.930
8  HP Designjet T520 Inkjet Large Format Printer ...   8749.950
9              Canon imageCLASS 2200 Advanced Copier   8399.976

In [137]:
query = """
SELECT Category,
COUNT(*) AS Total_Orders
FROM sales
GROUP BY Category
"""

pd.read_sql(query, conn)

          Category  Total_Orders
0        Furniture          2201
1  Office Supplies          6128
2       Technology          1865

In [138]:
query = """
SELECT Category,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Category
HAVING SUM(Sales) > 100000
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0        Furniture  754747.7613
1  Office Supplies  731893.3140
2       Technology  839893.2790

In [139]:
query = """
SELECT [Product Name],
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY [Product Name]
ORDER BY Total_Sales DESC
LIMIT 5
"""

pd.read_sql(query, conn)

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479

In [140]:
query = """
SELECT Region,
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY Region
ORDER BY Total_Sales DESC
"""

pd.read_sql(query, conn)

    Region  Total_Sales
0     West  739813.6085
1     East  691828.1680
2  Central  503170.6728
3    South  391721.9050

In [141]:
query = """
SELECT [Customer Name],
SUM(Sales) AS Total_Sales
FROM sales
GROUP BY [Customer Name]
ORDER BY Total_Sales DESC
LIMIT 10
"""

pd.read_sql(query, conn)

        Customer Name  Total_Sales
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

In [142]:
query = """
SELECT Category,
SUM(Profit) AS Total_Profit
FROM sales
GROUP BY Category
ORDER BY Total_Profit DESC
"""

pd.read_sql(query, conn)

          Category  Total_Profit
0       Technology   146543.3756
1  Office Supplies   126023.4434
2        Furniture    19729.9956

In [143]:
query = """
SELECT Category,
AVG(Sales) AS Average_Sales
FROM sales
GROUP BY Category
"""

pd.read_sql(query, conn)

          Category  Average_Sales
0        Furniture     342.911295
1  Office Supplies     119.434288
2       Technology     450.344922

# Key Insights

1. Technology category generated significant sales revenue.
2. Certain products contributed more sales than others.
3. Some customers generated higher revenue than the average customer.
4. Sales performance varied across regions.
5. Profitability differed among categories.